### ISSUE TITLE
Restoring System Backup Returns "Error 255"

### ISSUE THREAD

**Issue by ghost** [TeamWin/android_device_samsung_jackpot2lte#1]
Whenever I restore a TWRP backup of my previously used ROM, I get this this error from restoring System _all the time_:

"extractTarFork() process ended with ERROR: 255"

After that, the Restore process stops, rendering my backup as "corrupted".

OTHER INFO
TWRP Version: 3.5.2_9–0
TWRP Variant: Original
Picture: [See Here](https://drive.google.com/file/d/10OQ7vtwbenq-oOncJXHSOeym-sYISMjc/view?usp=drivesdk )
Logs: IDK how to get logs from recovery

**Comment by bigbiff** [comment]
I will have to close this issue within a couple of days if there are no debugging logs. It's impossible to figure out anything without the logs.

**Comment by ghost** [comment]
> I will have to close this issue within a couple of days if there are no debugging logs. It's impossible to figure out anything without the logs.

Where do the logs get stored when I save those? In internal storage, correct? I know that, in other ROM's, the location of logs can be stored on different locations. 

Hence I didn't post logs at the time of posting the issue.

**Comment by ghost** [comment]
Nevermind. The issue got resolved.

Here's what I did to resolve the issue:

In TWRP, go to Wipe >> Advanced Wipe. From there, toggle System.
Then, go to Repair or Change File System >> Change File System
Tap EXT4, then wipe.

After that, go back and tap Repair File System, then wipe.


Now I can restore all my TWRP backups :D
